backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'

handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

backend/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('book/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('book/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('book/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

backend/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        verbose_name='Картинка'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        unique_together = [['user', 'author']]

backend/posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'image')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Текст'}

backend/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment, Follow
from django.core.paginator import Paginator
from .forms import PostForm, CommentForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

User = get_user_model()


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/index.html', context)


def profile(request, username):
    profile_author = get_object_or_404(User, username=username)
    following = False
    post_list = profile_author.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    for follower in profile_author.following.all():
        if request.user == follower.user:
            following = True
            break
    context = {
        'profile': profile_author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.filter(post=post).all()
    form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html',
                  {'form': form, 'post': post, 'is_edit': True})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    following = request.user.follower.all()
    author_list = []
    for author in following:
        author_list.append(author.author.id)
    post_list = Post.objects.filter(author__in=author_list).order_by("-pub_date").all()
    page_number = request.GET.get("page")
    paginator = Paginator(post_list, 10)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, "posts/follow.html", context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    follow_check = Follow.objects.filter(user=request.user.id, author=author.id).exists()
    if not follow_check and author != request.user:
        Follow.objects.create(user=request.user, author=author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    profile_author = get_object_or_404(User, username=username)
    profile_author.following.filter(user=request.user).delete()
    return redirect('posts:profile', username=username)

backend/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
    {% if is_edit %}
        Редактировать запись
    {% else %}
        Добавить запись
    {% endif %}
{% endblock %}
{% block content %}
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                Редактировать запись
                {% else %}
                Добавить запись
                {% endif %}
              </div>
              <div class="card-body">
                  {% if is_edit %}
                  <form method="post" action="{% url 'posts:post_edit' post.id %}" enctype="multipart/form-data">
                  {% else %}
                <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
                  {% endif %}
                    {% csrf_token %}
                       {% for field in form %}
                        <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
                      {% endfor %}
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                      Сохранить
                      {% else %}
                      Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

backend/templates/posts/follow.html
{% extends 'base.html'%}
{% load thumbnail %}
{% block title %}Подписки{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
    <article>
    <ul>
        <li>
            Автор: {{ post.author }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date }}
        </li>
    </ul>
    <p>
        {{ post.text|linebreaks }}
    </p>
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
    </article>
        {% if not forloop.last %}
          <hr>
        {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}

{% endblock %}

backend/templates/posts/index.html
{% extends 'base.html'%}
{% load thumbnail %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% cache 20 index_page %}
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <article>
    <ul>
        <li>
            Название: <a href="{% url 'posts:post_detail' post.id %}"> {{ post.title }} </a>
        </li>
        <li>
            Автор: {{ post.author }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date }}
        </li>
    </ul>
    <p>
        {{ post.text|linebreaks }}
    </p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
    </article>
        {% if not forloop.last %}
          <hr>
        {% endif %}
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}
{% endcache %}
{% endblock %}

backend/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}{{ post|truncatewords:2 }}{% endblock %}
{% block content %}
<div class="row">
    <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                Дата публикации: {{ post.pub_date|date }}
            </li>
            {% if post.group %}
            <li class="list-group-item">
                Группа: {{ post.group }}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </li>
            {% endif %}
            <li class="list-group-item">
                Автор: {{ post.author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:  <span >{{ post.author.posts.all.count }}</span>
            </li>
            <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author %}">
                  все посты пользователя
                </a>
            </li>
            </ul>
            </aside>
            <article class="col-12 col-md-9">
              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img src="{{ im.url }}" width="960" height="339" alt="">
                {% endthumbnail %}
                <p>
                 {{ post.text|linebreaks }}
                </p>
                {% if post.author == user %}
                    <a class="btn btn-sm btn-primary" href="{% url 'posts:post_edit' post.id %}" role="button">Редактировать</a>
                {% endif %}

                {% if user.is_authenticated %}
                  <div class="card my-4">
                    <h5 class="card-header">Добавить комментарий:</h5>
                    <div class="card-body">
                      <form method="post" action="{% url 'posts:add_comment' post.id %}">
                        {% csrf_token %}
                        <div class="form-group mb-2">
                          {{ form.text|addclass:"form-control" }}
                        </div>
                        <button type="submit" class="btn btn-primary">Отправить</button>
                      </form>
                    </div>
                  </div>
                {% endif %}

                {% for comment in comments %}
                <div class="media mb-4">
                    <div class="media-body">
                        <h5 class="mt-0">
                            <a href="{% url 'posts:profile' comment.author.username %}">
                              {{ comment.author.username }}
                            </a>
                            </h5>
                            <p>
                             {{ comment.text }}
                            </p>
                    </div>
                </div>
                {% endfor %}
            </article>
</div>
{% endblock %}

backend/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Профайл пользователя {{ profile.get_full_name }}{% endblock %}
{% block content %}
<div class="mb-5">
  <h1>Все посты пользователя {{ profile.get_full_name }}</h1>
  <h3>Всего постов: {{ profile.posts.count }}</h3>
    {% if profile.username != user.username %}
  {% if following %}
    <a class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' profile.username %}" role="button">
      Отписаться
    </a>
  {% else %}
      <a class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' profile.username %}" role="button">
        Подписаться
      </a>
   {% endif %}
    {% endif %}
</div>
    {% for post in page_obj %}
            <article>
            <ul>
                <li>
                    Автор: {{ post.author }}
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date }}
                </li>
            </ul>
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
            <p>
                {{ post.text|linebreaks }}
            </p>
                <dl>
                    <dt>
                <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
                </dt>
                    <dt>
                     {% if post.group %}
                        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                    {% endif %}
                </dt>
                </dl>
            <hr>
            </article>
  {% endfor %}
        {% include 'posts/includes/paginator.html' %}
{% endblock %}