backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'

handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

backend/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('book/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('book/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('book/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

backend/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView, PasswordChangeView
from django.contrib.auth.views import PasswordResetView, PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetDoneView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('password_change/',
         PasswordChangeView.as_view(
             template_name="users/password_change_form.html"),
         name='password_change_form'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html'),
         name='password_reset_form'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_resent_confirm'),
]

backend/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'phone_number')


class PasswordChangeForm(forms.Form):
    password = forms.CharField(label='Текущий пароль')
    password_new = forms.CharField(label='Новый пароль')
    password_new_done = forms.CharField(label='Новый пароль (повторно)')

backend/users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm, PasswordChangeForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


class PasswordChange(CreateView):
    form_class = PasswordChangeForm
    template_name = 'users/password_change_form.html'

backend/templates/users/logged_out.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Вы вышли из системы</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>         
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">Выход</div>
              <div class="card-body"> <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row --> 
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

backend/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

backend/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}Пароль изменён {% endblock %}
{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
{% endblock %}

backend/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}Изменение пароля {% endblock %}
{% load user_filters %}
{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="">
                  {% csrf_token %}
                  {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
                  <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>

                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
{% endblock %}

backend/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}

{% if validlink %}

<!-- Тут код формы из шаблона -->

{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Ошибка</div>
      <div class="card-body">
        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endif %}

{% endblock %} 

backend/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}Новый пароль{% endblock %}
{% load user_filters %}
{% block content %}
{% if validlink %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
                  {% csrf_token %}
                  {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
                  {% csrf_token %}
                  <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- если использована неправильная ссылка -->
{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Ошибка</div>
      <div class="card-body">
        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endif %}
{% endblock %}

backend/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно {% endblock %}
{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Отправлено письмо
              </div>
              <div class="card-body">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
{% endblock %}

backend/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title %}Сброс пароля {% endblock %}
{% block content %}
{% load user_filters %}
<main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body"> 
                <form method="post" action="{% url 'users:password_reset_form' %}">
                  {% csrf_token %}
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
                  {% csrf_token %}
                  <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
    </main>
{% endblock %}

backend/templates/users/signup.html
{% extends 'base.html' %}
{% block title %}Зарегистрироваться{% endblock %}
{% load user_filters %}
{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
            <div class="col-md-8 p-5">
              <div class="card">
                <div class="card-header">
                  Зарегистрироваться
                </div>
                <div class="card-body">
                  <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
                    {% csrf_token %}
                  {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
                  {% csrf_token %}
                  <button type="submit" class="btn btn-primary">
                    Зарегистрироваться
                    </button>
                  </form>
                </div> <!-- card body -->
              </div> <!-- card -->
            </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
{% endblock %}